name: ocr_encoder
backend: "onnxruntime"
max_batch_size: 0

input [
    {
        name: "src"
        data_type: TYPE_FLOAT32
        dims: [ -1, -1, 256 ]
    }
]

output [
    {
        name: "encoder_outputs"
        data_type: TYPE_FLOAT32
        dims: [ -1, 1, 512 ]
    },
    {
        name: "hidden"
        data_type: TYPE_FLOAT32
        dims: [ 1, 256 ]
    }
]