name: ocr_encoder
backend: "onnxruntime"
max_batch_size: 0

input [
    {
        name: "tgt"
        data_type: TYPE_INT64
        dims: [ 1 ]
    },
    {
        name: "hidden"
        data_type: TYPE_FLOAT32
        dims: [ 1, 256 ]
    },
    {
        name: "encoder_outputs"
        data_type: TYPE_FLOAT32
        dims: [ -1, 1, 512 ]
    }
]

output [
    {
        name: "output"
        data_type: TYPE_FLOAT32
        dims: [ 1, 233 ]
    },
    {
        name: "hidden_out"
        data_type: TYPE_FLOAT32
        dims: [ 1, 256 ]
    },
    {
        name: "last"
        data_type: TYPE_FLOAT32
        dims: [ -1, -1 ]
    }
]